name: windshear_example
channels:
  - informaticslab
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - dask-kubernetes
  - jupyterlab=0.35.6
  - geoviews
  - itkwidgets
  - jade_utils
  - jupyterlab
  - mo_aws_earth
  - numpy
  - panel
  - python=3
  - qrcode
