#!/bin/bash

# Install a JupyterLab extensions for wind_shear.ipynb
jupyter labextension update --all
jupyter labextension install \
@jupyter-widgets/jupyterlab-manager \
@pyviz/jupyterlab_pyviz \
dask-labextension \
itk-jupyter-widgets \
jupyter-matplotlib \
jupyterlab-datawidgets \
jupyterlab_bokeh 
